package com.newuniverse.nusmp.client;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/** 0.49: Rouge, a small cat of red thread sitting upright (geometry and texture from tools/gen_rouge_cat.py). */
public class RougeCatModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath("nusmp", "rouge_cat"), "main");

    private final ModelPart root, head, tail;

    public RougeCatModel(ModelPart root) {
        this.root = root;
        this.head = root.getChild("head");
        this.tail = root.getChild("tail");
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        // <generated by tools/gen_rouge_cat.py>
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2f, -6f, -2f, 4f, 6f, 4f), PartPose.offsetAndRotation(0f, 22f, 0f, -0.45f, 0f, 0f));
        PartDefinition p_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 10).addBox(-2.5f, -4f, -2f, 5f, 4f, 4f).texOffs(18, 10).addBox(-2.5f, -5.5f, -0.5f, 1f, 2f, 1f).texOffs(18, 10).mirror().addBox(1.5f, -5.5f, -0.5f, 1f, 2f, 1f).texOffs(22, 13).addBox(-1f, -1.6f, -3f, 2f, 1.5f, 1f), PartPose.offsetAndRotation(0f, 16.8f, -1.4f, 0f, 0f, 0f));
        PartDefinition p_leg_r = root.addOrReplaceChild("leg_r", CubeListBuilder.create().texOffs(24, 0).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-1f, 19f, -1.6f, 0f, 0f, 0f));
        PartDefinition p_leg_l = root.addOrReplaceChild("leg_l", CubeListBuilder.create().texOffs(24, 0).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(1f, 19f, -1.6f, 0f, 0f, 0f));
        PartDefinition p_haunch_r = root.addOrReplaceChild("haunch_r", CubeListBuilder.create().texOffs(0, 18).addBox(-1f, -1.5f, -1.5f, 2f, 2f, 3f), PartPose.offsetAndRotation(-1.6f, 22.5f, 0.6f, 0f, 0f, 0f));
        PartDefinition p_haunch_l = root.addOrReplaceChild("haunch_l", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-1f, -1.5f, -1.5f, 2f, 2f, 3f), PartPose.offsetAndRotation(1.6f, 22.5f, 0.6f, 0f, 0f, 0f));
        PartDefinition p_tail = root.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(10, 18).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 5f), PartPose.offsetAndRotation(0f, 23.2f, 2f, 0f, 0.9f, 0f));
        PartDefinition p_tail_tip = p_tail.addOrReplaceChild("tail_tip", CubeListBuilder.create().texOffs(10, 18).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 4f), PartPose.offsetAndRotation(0f, 0f, 4.8f, 0f, 1.2f, 0f));
        // </generated>
        return LayerDefinition.create(mesh, 32, 32);
    }

    /** A slow look round, ears and tail alive. */
    public void animate(float age) {
        root.getAllParts().forEach(ModelPart::resetPose);
        head.yRot = Mth.sin(age * 0.04f) * 0.6f;
        head.xRot = Mth.sin(age * 0.07f) * 0.08f;
        tail.yRot += Mth.sin(age * 0.11f) * 0.25f;
    }

    public void render(PoseStack pose, VertexConsumer vc, int light, int overlay, int color) { root.render(pose, vc, light, overlay, color); }
}
