package com.newuniverse.nusmp.client;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.newuniverse.nusmp.entity.ZagredBossEntity;
import net.minecraft.client.model.ArmedModel;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.HumanoidArm;

/**
 * 0.48: Zagred's true form in Minecraft cuboids (replaces the 0.47 humanoid). Geometry comes from tools/gen_zagred_true_form.py
 * (the same part list paints textures/entity/zagred_true*.png), animation is here:
 * <ul>
 *   <li>Hover: the whole body bobs on a sine wave (y = sin(t * 0.1) * 1.2 px) and floats higher from phase 2.</li>
 *   <li>Wings: two segments each, slow beats at rest, fast in combat; the outer segment trails the inner one.</li>
 *   <li>Tail: five segments swaying in a travelling wave, the spade last.</li>
 *   <li>Pose (the reference pose): standing tall, wings spread wide, long arms hanging a little out from the body with the claws
 *       curled. Casting raises both arms forward, claws open; a melee swing brings the right claws down.</li>
 * </ul>
 */
public class ZagredModel extends EntityModel<ZagredBossEntity> implements ArmedModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath("nusmp", "zagred_true"), "main");

    private final ModelPart root, body, head, armR, armL, forearmR, forearmL, handR, handL, legR, legL, shinR, shinL,
            wingR, wingL, wing2R, wing2L;
    private final ModelPart[] tail = new ModelPart[5], clawsR = new ModelPart[3], clawsL = new ModelPart[3];

    public ZagredModel(ModelPart modelRoot) {
        root = modelRoot.getChild("root");
        body = root.getChild("body");
        head = root.getChild("head");
        armR = root.getChild("arm_r"); armL = root.getChild("arm_l");
        forearmR = armR.getChild("forearm_r"); forearmL = armL.getChild("forearm_l");
        handR = forearmR.getChild("hand_r"); handL = forearmL.getChild("hand_l");
        for (int k = 0; k < 3; k++) { clawsR[k] = handR.getChild("claw_r" + k); clawsL[k] = handL.getChild("claw_l" + k); }
        legR = root.getChild("leg_r"); legL = root.getChild("leg_l");
        shinR = legR.getChild("shin_r"); shinL = legL.getChild("shin_l");
        wingR = body.getChild("wing_r"); wingL = body.getChild("wing_l");
        wing2R = wingR.getChild("wing2_r"); wing2L = wingL.getChild("wing2_l");
        tail[0] = body.getChild("tail1");
        for (int k = 1; k < 4; k++) tail[k] = tail[k - 1].getChild("tail" + (k + 1));
        tail[4] = tail[3].getChild("spade");
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        // <generated by tools/gen_zagred_true_form.py>
        PartDefinition p_root = mesh.getRoot().addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0f, -9f, 0f, 0f, 0f, 0f));
        PartDefinition p_body = p_root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5f, 0f, -2.5f, 9f, 13f, 5f).texOffs(30, 0).addBox(-3.5f, 1.5f, -3.3f, 7f, 7f, 1f).texOffs(48, 0).addBox(-4f, 13f, -2.5f, 8f, 3f, 5f), PartPose.offsetAndRotation(0f, 0f, 0f, 0f, 0f, 0f));
        PartDefinition p_head = p_root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 20).addBox(-4f, -8f, -4f, 8f, 8f, 8f).texOffs(32, 20).addBox(-4.5f, -8.6f, -4.5f, 9f, 4f, 9f).texOffs(68, 20).addBox(-4f, -6f, 3.5f, 8f, 11f, 2f), PartPose.offsetAndRotation(0f, 0f, 0f, 0f, 0f, 0f));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(88, 20).addBox(-3f, -0.5f, -0.5f, 3f, 1f, 1f), PartPose.offsetAndRotation(-4f, -4.5f, 0f, 0f, 0f, 0.35f));
        PartDefinition p_horn_r = p_head.addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(96, 20).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(-2.6f, -7.6f, -1.5f, -0.35f, 0f, -0.5f));
        PartDefinition p_horn_r_mid = p_horn_r.addOrReplaceChild("horn_r_mid", CubeListBuilder.create().texOffs(104, 20).addBox(-0.5f, -4f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, -2.8f, 0f, -0.45f, 0f, 0.25f));
        PartDefinition p_horn_r_tip = p_horn_r_mid.addOrReplaceChild("horn_r_tip", CubeListBuilder.create().texOffs(108, 20).addBox(-0.5f, -3f, -0.5f, 1f, 3f, 1f), PartPose.offsetAndRotation(0f, -3.8f, 0f, -0.5f, 0f, 0.2f));
        PartDefinition p_arm_r = p_root.addOrReplaceChild("arm_r", CubeListBuilder.create().texOffs(0, 38).addBox(-1.5f, -1f, -1.5f, 3f, 9f, 3f), PartPose.offsetAndRotation(-6f, 1.5f, 0f, 0f, 0f, 0.18f));
        PartDefinition p_forearm_r = p_arm_r.addOrReplaceChild("forearm_r", CubeListBuilder.create().texOffs(12, 38).addBox(-1.5f, 0f, -1.5f, 3f, 9f, 3f), PartPose.offsetAndRotation(0f, 8f, 0f, -0.2f, 0f, 0f));
        PartDefinition p_hand_r = p_forearm_r.addOrReplaceChild("hand_r", CubeListBuilder.create().texOffs(24, 38).addBox(-1.5f, 0f, -1.5f, 3f, 2f, 3f), PartPose.offsetAndRotation(0f, 9f, 0f, 0f, 0f, 0f));
        PartDefinition p_claw_r0 = p_hand_r.addOrReplaceChild("claw_r0", CubeListBuilder.create().texOffs(36, 38).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-1f, 1.8f, -1f, -0.35f, 0f, -0.12f));
        PartDefinition p_claw_r1 = p_hand_r.addOrReplaceChild("claw_r1", CubeListBuilder.create().texOffs(36, 38).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(0f, 1.8f, -1f, -0.35f, 0f, 0f));
        PartDefinition p_claw_r2 = p_hand_r.addOrReplaceChild("claw_r2", CubeListBuilder.create().texOffs(36, 38).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(1f, 1.8f, -1f, -0.35f, 0f, 0.12f));
        PartDefinition p_leg_r = p_root.addOrReplaceChild("leg_r", CubeListBuilder.create().texOffs(0, 52).addBox(-2f, 0f, -2f, 4f, 7f, 4f), PartPose.offsetAndRotation(-2.4f, 16f, 0f, 0f, 0f, 0f));
        PartDefinition p_shin_r = p_leg_r.addOrReplaceChild("shin_r", CubeListBuilder.create().texOffs(16, 52).addBox(-1.5f, 0f, -1.5f, 3f, 8f, 3f), PartPose.offsetAndRotation(0f, 7f, 0f, 0f, 0f, 0f));
        PartDefinition p_foot_r = p_shin_r.addOrReplaceChild("foot_r", CubeListBuilder.create().texOffs(28, 52).addBox(-1.5f, 0f, -3.5f, 3f, 2f, 5f), PartPose.offsetAndRotation(0f, 8f, 0f, 0f, 0f, 0f));
        PartDefinition p_toe_r0 = p_foot_r.addOrReplaceChild("toe_r0", CubeListBuilder.create().texOffs(44, 52).addBox(-0.5f, 0f, -3f, 1f, 1f, 3f), PartPose.offsetAndRotation(-1f, 1f, -3.5f, 0.3f, 0f, 0f));
        PartDefinition p_toe_r1 = p_foot_r.addOrReplaceChild("toe_r1", CubeListBuilder.create().texOffs(44, 52).addBox(-0.5f, 0f, -3f, 1f, 1f, 3f), PartPose.offsetAndRotation(0f, 1f, -3.5f, 0.3f, 0f, 0f));
        PartDefinition p_toe_r2 = p_foot_r.addOrReplaceChild("toe_r2", CubeListBuilder.create().texOffs(44, 52).addBox(-0.5f, 0f, -3f, 1f, 1f, 3f), PartPose.offsetAndRotation(1f, 1f, -3.5f, 0.3f, 0f, 0f));
        PartDefinition p_wing_r = p_body.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(0, 66).addBox(-14f, -1f, -1f, 14f, 2f, 2f), PartPose.offsetAndRotation(-2f, 2f, 2.6f, 0f, 0.55f, -0.3f));
        PartDefinition p_membrane_r = p_wing_r.addOrReplaceChild("membrane_r", CubeListBuilder.create().texOffs(0, 72).addBox(-14f, 0f, 0f, 14f, 18f, 0f), PartPose.offsetAndRotation(0f, 1f, 0f, 0f, 0f, 0f));
        PartDefinition p_wing2_r = p_wing_r.addOrReplaceChild("wing2_r", CubeListBuilder.create().texOffs(32, 66).addBox(-14f, -1f, -1f, 14f, 2f, 2f), PartPose.offsetAndRotation(-14f, 0f, 0f, 0f, 0f, 0.65f));
        PartDefinition p_membrane2_r = p_wing2_r.addOrReplaceChild("membrane2_r", CubeListBuilder.create().texOffs(28, 72).addBox(-14f, 0f, 0f, 14f, 22f, 0f), PartPose.offsetAndRotation(0f, 1f, 0f, 0f, 0f, 0f));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(88, 20).mirror().addBox(0f, -0.5f, -0.5f, 3f, 1f, 1f), PartPose.offsetAndRotation(4f, -4.5f, 0f, 0f, 0f, -0.35f));
        PartDefinition p_horn_l = p_head.addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(96, 20).mirror().addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(2.6f, -7.6f, -1.5f, -0.35f, 0f, 0.5f));
        PartDefinition p_horn_l_mid = p_horn_l.addOrReplaceChild("horn_l_mid", CubeListBuilder.create().texOffs(104, 20).mirror().addBox(-0.5f, -4f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, -2.8f, 0f, -0.45f, 0f, -0.25f));
        PartDefinition p_horn_l_tip = p_horn_l_mid.addOrReplaceChild("horn_l_tip", CubeListBuilder.create().texOffs(108, 20).mirror().addBox(-0.5f, -3f, -0.5f, 1f, 3f, 1f), PartPose.offsetAndRotation(0f, -3.8f, 0f, -0.5f, 0f, -0.2f));
        PartDefinition p_arm_l = p_root.addOrReplaceChild("arm_l", CubeListBuilder.create().texOffs(0, 38).mirror().addBox(-1.5f, -1f, -1.5f, 3f, 9f, 3f), PartPose.offsetAndRotation(6f, 1.5f, 0f, 0f, 0f, -0.18f));
        PartDefinition p_forearm_l = p_arm_l.addOrReplaceChild("forearm_l", CubeListBuilder.create().texOffs(12, 38).mirror().addBox(-1.5f, 0f, -1.5f, 3f, 9f, 3f), PartPose.offsetAndRotation(0f, 8f, 0f, -0.2f, 0f, 0f));
        PartDefinition p_hand_l = p_forearm_l.addOrReplaceChild("hand_l", CubeListBuilder.create().texOffs(24, 38).mirror().addBox(-1.5f, 0f, -1.5f, 3f, 2f, 3f), PartPose.offsetAndRotation(0f, 9f, 0f, 0f, 0f, 0f));
        PartDefinition p_claw_l0 = p_hand_l.addOrReplaceChild("claw_l0", CubeListBuilder.create().texOffs(36, 38).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-1f, 1.8f, -1f, -0.35f, 0f, -0.12f));
        PartDefinition p_claw_l1 = p_hand_l.addOrReplaceChild("claw_l1", CubeListBuilder.create().texOffs(36, 38).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(0f, 1.8f, -1f, -0.35f, 0f, 0f));
        PartDefinition p_claw_l2 = p_hand_l.addOrReplaceChild("claw_l2", CubeListBuilder.create().texOffs(36, 38).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(1f, 1.8f, -1f, -0.35f, 0f, 0.12f));
        PartDefinition p_leg_l = p_root.addOrReplaceChild("leg_l", CubeListBuilder.create().texOffs(0, 52).mirror().addBox(-2f, 0f, -2f, 4f, 7f, 4f), PartPose.offsetAndRotation(2.4f, 16f, 0f, 0f, 0f, 0f));
        PartDefinition p_shin_l = p_leg_l.addOrReplaceChild("shin_l", CubeListBuilder.create().texOffs(16, 52).mirror().addBox(-1.5f, 0f, -1.5f, 3f, 8f, 3f), PartPose.offsetAndRotation(0f, 7f, 0f, 0f, 0f, 0f));
        PartDefinition p_foot_l = p_shin_l.addOrReplaceChild("foot_l", CubeListBuilder.create().texOffs(28, 52).mirror().addBox(-1.5f, 0f, -3.5f, 3f, 2f, 5f), PartPose.offsetAndRotation(0f, 8f, 0f, 0f, 0f, 0f));
        PartDefinition p_toe_l0 = p_foot_l.addOrReplaceChild("toe_l0", CubeListBuilder.create().texOffs(44, 52).mirror().addBox(-0.5f, 0f, -3f, 1f, 1f, 3f), PartPose.offsetAndRotation(-1f, 1f, -3.5f, 0.3f, 0f, 0f));
        PartDefinition p_toe_l1 = p_foot_l.addOrReplaceChild("toe_l1", CubeListBuilder.create().texOffs(44, 52).mirror().addBox(-0.5f, 0f, -3f, 1f, 1f, 3f), PartPose.offsetAndRotation(0f, 1f, -3.5f, 0.3f, 0f, 0f));
        PartDefinition p_toe_l2 = p_foot_l.addOrReplaceChild("toe_l2", CubeListBuilder.create().texOffs(44, 52).mirror().addBox(-0.5f, 0f, -3f, 1f, 1f, 3f), PartPose.offsetAndRotation(1f, 1f, -3.5f, 0.3f, 0f, 0f));
        PartDefinition p_wing_l = p_body.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(0, 66).mirror().addBox(0f, -1f, -1f, 14f, 2f, 2f), PartPose.offsetAndRotation(2f, 2f, 2.6f, 0f, -0.55f, 0.3f));
        PartDefinition p_membrane_l = p_wing_l.addOrReplaceChild("membrane_l", CubeListBuilder.create().texOffs(0, 72).mirror().addBox(0f, 0f, 0f, 14f, 18f, 0f), PartPose.offsetAndRotation(0f, 1f, 0f, 0f, 0f, 0f));
        PartDefinition p_wing2_l = p_wing_l.addOrReplaceChild("wing2_l", CubeListBuilder.create().texOffs(32, 66).mirror().addBox(0f, -1f, -1f, 14f, 2f, 2f), PartPose.offsetAndRotation(14f, 0f, 0f, 0f, 0f, -0.65f));
        PartDefinition p_membrane2_l = p_wing2_l.addOrReplaceChild("membrane2_l", CubeListBuilder.create().texOffs(28, 72).mirror().addBox(0f, 0f, 0f, 14f, 22f, 0f), PartPose.offsetAndRotation(0f, 1f, 0f, 0f, 0f, 0f));
        PartDefinition p_tail1 = p_body.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(56, 38).addBox(-1.5f, -1.5f, 0f, 3f, 3f, 7f), PartPose.offsetAndRotation(0f, 14f, 2.5f, -0.75f, 0f, 0f));
        PartDefinition p_tail2 = p_tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(76, 38).addBox(-1f, -1f, 0f, 2f, 2f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.5f, -0.2f, 0f, 0f));
        PartDefinition p_tail3 = p_tail2.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(94, 38).addBox(-1f, -1f, 0f, 2f, 2f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.5f, 0.25f, 0f, 0f));
        PartDefinition p_tail4 = p_tail3.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(56, 50).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.5f, 0.35f, 0f, 0f));
        PartDefinition p_spade = p_tail4.addOrReplaceChild("spade", CubeListBuilder.create().texOffs(72, 50).addBox(-2.5f, -0.5f, 0f, 5f, 1f, 5f), PartPose.offsetAndRotation(0f, 0f, 6.5f, 0f, 0f, 0f));
        // </generated>
        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(ZagredBossEntity e, float limbSwing, float limbAmount, float age, float yaw, float pitch) {
        root.getAllParts().forEach(ModelPart::resetPose);
        int state = e.clientState();
        boolean fighting = state >= ZagredBossEntity.STATE_COMBAT;
        root.y += Mth.sin(age * 0.1f) * 1.2f - (e.phase() >= 2 ? 2f : 0f);
        head.yRot = yaw * Mth.DEG_TO_RAD;
        head.xRot = pitch * Mth.DEG_TO_RAD;
        if (state == ZagredBossEntity.STATE_IDLE) head.yRot += Mth.sin(age * 0.03f) * 0.25f;            // a slow, curious look round

        float walk = Mth.cos(limbSwing * 0.6662f) * limbAmount;
        legR.xRot = walk * 0.9f; legL.xRot = -walk * 0.9f;
        shinR.xRot = Math.max(0, -walk) * 0.9f; shinL.xRot = Math.max(0, walk) * 0.9f;
        armR.xRot += -walk * 0.45f; armL.xRot += walk * 0.45f;
        armR.zRot += Mth.sin(age * 0.06f) * 0.04f; armL.zRot -= Mth.sin(age * 0.06f) * 0.04f;          // breathing
        for (ModelPart c : clawsR) c.xRot -= 0.15f + 0.1f * Mth.sin(age * 0.08f);
        for (ModelPart c : clawsL) c.xRot -= 0.15f + 0.1f * Mth.sin(age * 0.08f + 1);

        float beat = Mth.sin(age * (fighting ? 0.32f : 0.11f)), lag = Mth.sin(age * (fighting ? 0.32f : 0.11f) - 0.8f);
        float spread = fighting ? 0.25f : 0.1f;
        wingR.yRot += beat * 0.35f - spread; wingL.yRot -= beat * 0.35f - spread;
        wingR.zRot += beat * 0.12f; wingL.zRot -= beat * 0.12f;
        wing2R.zRot += lag * 0.25f; wing2L.zRot -= lag * 0.25f;

        for (int k = 0; k < tail.length; k++) {
            tail[k].yRot = Mth.sin(age * 0.12f - k * 0.7f) * (0.18f + 0.05f * k);
            tail[k].xRot += Mth.sin(age * 0.07f - k * 0.5f) * 0.06f;
        }

        if (state == ZagredBossEntity.STATE_CASTING) {                        // both hands raised forward, claws spread
            armR.xRot = -1.7f; armR.zRot = 0.25f; armL.xRot = -1.7f; armL.zRot = -0.25f;
            forearmR.xRot = -0.35f; forearmL.xRot = -0.35f;
            for (int k = 0; k < 3; k++) { clawsR[k].xRot = -0.9f; clawsR[k].zRot = (k - 1) * 0.35f; clawsL[k].xRot = -0.9f; clawsL[k].zRot = (k - 1) * 0.35f; }
        }
        if (attackTime > 0) {                                                // a raking claw swing
            float s = Mth.sin(attackTime * Mth.PI);
            armR.xRot = -2.4f + s * 2.6f;
            armR.yRot = -0.3f * s;
            forearmR.xRot = -0.5f * (1 - s);
        }
    }

    @Override
    public void renderToBuffer(PoseStack pose, VertexConsumer vc, int light, int overlay, int color) {
        root.render(pose, vc, light, overlay, color);
    }

    @Override
    public void translateToHand(HumanoidArm arm, PoseStack pose) {
        root.translateAndRotate(pose);
        boolean right = arm == HumanoidArm.RIGHT;
        (right ? armR : armL).translateAndRotate(pose);
        (right ? forearmR : forearmL).translateAndRotate(pose);
        (right ? handR : handL).translateAndRotate(pose);
    }
}
