package com.newuniverse.nusmp.client;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.newuniverse.nusmp.entity.ZagredBossEntity;
import net.minecraft.client.model.ArmedModel;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.HumanoidArm;

/**
 * 0.48: Zagred's true form in Minecraft cuboids (replaces the 0.47 humanoid). Geometry comes from tools/gen_zagred_true_form.py
 * (the same part list paints textures/entity/zagred_true*.png), animation is here:
 * <ul>
 *   <li>Hover: the whole body bobs on a sine wave (y = sin(t * 0.1) * 1.2 px) and floats higher from phase 2.</li>
 *   <li>Wings: two segments each, slow beats at rest, fast in combat; the outer segment trails the inner one.</li>
 *   <li>Tail: five segments swaying in a travelling wave, the spade last.</li>
 *   <li>Pose (the reference pose): standing tall, wings spread wide, long arms hanging a little out from the body with the claws
 *       curled. Casting raises both arms forward, claws open; a melee swing brings the right claws down.</li>
 * </ul>
 */
public class ZagredModel extends EntityModel<ZagredBossEntity> implements ArmedModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath("nusmp", "zagred_true"), "main");

    private final ModelPart root, body, head, armR, armL, forearmR, forearmL, handR, handL, legR, legL, shinR, shinL,
            wingR, wingL, wing2R, wing2L;
    static final int TAIL = 8;
    private final ModelPart[] tail = new ModelPart[TAIL], clawsR = new ModelPart[4], clawsL = new ModelPart[4];

    public ZagredModel(ModelPart modelRoot) {
        root = modelRoot.getChild("root");
        body = root.getChild("body");
        head = root.getChild("head");
        armR = root.getChild("arm_r"); armL = root.getChild("arm_l");
        forearmR = armR.getChild("forearm_r"); forearmL = armL.getChild("forearm_l");
        handR = forearmR.getChild("hand_r"); handL = forearmL.getChild("hand_l");
        for (int k = 0; k < 4; k++) { clawsR[k] = handR.getChild("claw_r" + k); clawsL[k] = handL.getChild("claw_l" + k); }
        legR = root.getChild("leg_r"); legL = root.getChild("leg_l");
        shinR = legR.getChild("shin_r"); shinL = legL.getChild("shin_l");
        wingR = body.getChild("wing_r"); wingL = body.getChild("wing_l");
        wing2R = wingR.getChild("wing2_r"); wing2L = wingL.getChild("wing2_l");
        tail[0] = body.getChild("tail1");
        for (int k = 1; k < TAIL; k++) tail[k] = tail[k - 1].getChild("tail" + (k + 1));
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        // <generated by tools/gen_zagred_true_form.py>
        PartDefinition p_root = mesh.getRoot().addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0f, -25.5f, 0f, 0f, 0f, 0f));
        PartDefinition p_body = p_root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 40).addBox(-1.25f, -0.5f, -1.25f, 2.5f, 5f, 2.5f).texOffs(32, 26).addBox(-3.5f, 4f, -2f, 7f, 8f, 4f).texOffs(82, 26).addBox(-2f, 4.5f, -2.4f, 4f, 8f, 1f).texOffs(12, 40).addBox(-2.25f, 12f, -1.5f, 4.5f, 5f, 3f).texOffs(60, 40).addBox(-3f, 17f, -1.75f, 6f, 3f, 3.5f).texOffs(28, 40).addBox(-6f, 2.6f, -2f, 4f, 4f, 4f).texOffs(28, 40).mirror().addBox(2f, 2.6f, -2f, 4f, 4f, 4f).texOffs(22, 48).addBox(-4.5f, 2f, 0f, 2f, 2f, 2f).texOffs(22, 48).mirror().addBox(2.5f, 2f, 0f, 2f, 2f, 2f).texOffs(22, 48).addBox(-4.5f, 6.5f, -2.2f, 2f, 2f, 2f).texOffs(22, 48).mirror().addBox(2.5f, 6.5f, -2.2f, 2f, 2f, 2f).texOffs(80, 40).addBox(-5f, 8.5f, 0.5f, 3f, 3f, 3f).texOffs(80, 40).mirror().addBox(2f, 8.5f, 0.5f, 3f, 3f, 3f), PartPose.offsetAndRotation(0f, 0f, 0f, 0f, 0f, 0f));
        PartDefinition p_head = p_root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 26).addBox(-3f, -8f, -3.2f, 6f, 8f, 6f).texOffs(54, 26).addBox(-3.5f, -9f, -3.6f, 7f, 4f, 7f).texOffs(92, 26).addBox(-3.4f, -6.5f, 2.4f, 7f, 7f, 2f), PartPose.offsetAndRotation(0f, 0f, 0f, 0f, 0f, 0f));
        PartDefinition p_hair_spike0 = p_head.addOrReplaceChild("hair_spike0", CubeListBuilder.create().texOffs(120, 40).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(-2.5f, -8.5f, -2f, -0.4f, 0f, 0.5f));
        PartDefinition p_hair_spike1 = p_head.addOrReplaceChild("hair_spike1", CubeListBuilder.create().texOffs(120, 40).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(1.5f, -9f, -1f, 0.2f, 0f, -0.4f));
        PartDefinition p_hair_spike2 = p_head.addOrReplaceChild("hair_spike2", CubeListBuilder.create().texOffs(120, 40).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(-0.5f, -9.5f, 1f, 0.5f, 0f, 0.1f));
        PartDefinition p_hair_spike3 = p_head.addOrReplaceChild("hair_spike3", CubeListBuilder.create().texOffs(120, 40).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(2.5f, -7.5f, 1.5f, 0.6f, 0f, -0.8f));
        PartDefinition p_hair_spike4 = p_head.addOrReplaceChild("hair_spike4", CubeListBuilder.create().texOffs(120, 40).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(-3.5f, -7f, 1f, 0.3f, 0f, 0.9f));
        PartDefinition p_hair_spike5 = p_head.addOrReplaceChild("hair_spike5", CubeListBuilder.create().texOffs(120, 40).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(0.5f, -9f, -2.5f, -0.7f, 0f, -0.2f));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(48, 53).addBox(-6f, -0.5f, -0.5f, 6f, 1f, 1f), PartPose.offsetAndRotation(-3f, -4.8f, 0f, 0f, 0f, -0.15f));
        PartDefinition p_horn_r = p_head.addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(0, 48).addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(-1.8f, -8.6f, -0.5f, -0.15f, 0f, -0.35f));
        PartDefinition p_horn_r_mid = p_horn_r.addOrReplaceChild("horn_r_mid", CubeListBuilder.create().texOffs(30, 48).addBox(-0.5f, -3f, -0.5f, 1f, 3f, 1f), PartPose.offsetAndRotation(0f, -2.8f, 0f, 0.1f, 0f, 0.35f));
        PartDefinition p_horn_r_tip = p_horn_r_mid.addOrReplaceChild("horn_r_tip", CubeListBuilder.create().texOffs(44, 53).addBox(-0.5f, -2f, -0.5f, 1f, 2f, 1f), PartPose.offsetAndRotation(0f, -2.8f, 0f, 0.15f, 0f, 0.45f));
        PartDefinition p_arm_r = p_root.addOrReplaceChild("arm_r", CubeListBuilder.create().texOffs(108, 0).addBox(-1f, -1f, -1f, 2f, 13f, 2f), PartPose.offsetAndRotation(-4.5f, 5.5f, 0f, 0f, 0f, 0.22f));
        PartDefinition p_forearm_r = p_arm_r.addOrReplaceChild("forearm_r", CubeListBuilder.create().texOffs(24, 26).addBox(-1f, 0f, -1f, 2f, 12f, 2f), PartPose.offsetAndRotation(0f, 12f, 0f, -0.15f, 0f, 0f));
        PartDefinition p_hand_r = p_forearm_r.addOrReplaceChild("hand_r", CubeListBuilder.create().texOffs(92, 40).addBox(-1.25f, 0f, -1.25f, 2.5f, 2.5f, 2.5f), PartPose.offsetAndRotation(0f, 12f, 0f, 0f, 0f, 0f));
        PartDefinition p_claw_r0 = p_hand_r.addOrReplaceChild("claw_r0", CubeListBuilder.create().texOffs(104, 40).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-0.9f, 2.2f, -0.5f, -0.35f, 0f, -0.27f));
        PartDefinition p_claw_r0_tip = p_claw_r0.addOrReplaceChild("claw_r0_tip", CubeListBuilder.create().texOffs(8, 48).addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_claw_r1 = p_hand_r.addOrReplaceChild("claw_r1", CubeListBuilder.create().texOffs(104, 40).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-0.3f, 2.2f, -0.5f, -0.35f, 0f, -0.09f));
        PartDefinition p_claw_r1_tip = p_claw_r1.addOrReplaceChild("claw_r1_tip", CubeListBuilder.create().texOffs(8, 48).addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_claw_r2 = p_hand_r.addOrReplaceChild("claw_r2", CubeListBuilder.create().texOffs(104, 40).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(0.3f, 2.2f, -0.5f, -0.35f, 0f, 0.09f));
        PartDefinition p_claw_r2_tip = p_claw_r2.addOrReplaceChild("claw_r2_tip", CubeListBuilder.create().texOffs(8, 48).addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_claw_r3 = p_hand_r.addOrReplaceChild("claw_r3", CubeListBuilder.create().texOffs(104, 40).addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(0.9f, 2.2f, -0.5f, -0.35f, 0f, 0.27f));
        PartDefinition p_claw_r3_tip = p_claw_r3.addOrReplaceChild("claw_r3_tip", CubeListBuilder.create().texOffs(8, 48).addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_leg_r = p_root.addOrReplaceChild("leg_r", CubeListBuilder.create().texOffs(88, 0).addBox(-1.25f, 0f, -1.25f, 2.5f, 14f, 2.5f), PartPose.offsetAndRotation(-1.5f, 20f, 0f, 0f, 0f, 0f));
        PartDefinition p_shin_r = p_leg_r.addOrReplaceChild("shin_r", CubeListBuilder.create().texOffs(100, 0).addBox(-1f, 0f, -1f, 2f, 14f, 2f), PartPose.offsetAndRotation(0f, 14f, 0f, 0f, 0f, 0f));
        PartDefinition p_foot_r = p_shin_r.addOrReplaceChild("foot_r", CubeListBuilder.create().texOffs(108, 40).addBox(-1f, 0f, -2.5f, 2f, 1.5f, 3.5f), PartPose.offsetAndRotation(0f, 14f, 0f, 0f, 0f, 0f));
        PartDefinition p_toe_r0 = p_foot_r.addOrReplaceChild("toe_r0", CubeListBuilder.create().texOffs(12, 48).addBox(-0.5f, -0.5f, -4f, 1f, 1f, 4f), PartPose.offsetAndRotation(-0.7f, 0.8f, -2.5f, 0.25f, -0.25f, 0f));
        PartDefinition p_toe_r1 = p_foot_r.addOrReplaceChild("toe_r1", CubeListBuilder.create().texOffs(12, 48).addBox(-0.5f, -0.5f, -4f, 1f, 1f, 4f), PartPose.offsetAndRotation(0f, 0.8f, -2.5f, 0.25f, 0f, 0f));
        PartDefinition p_toe_r2 = p_foot_r.addOrReplaceChild("toe_r2", CubeListBuilder.create().texOffs(12, 48).addBox(-0.5f, -0.5f, -4f, 1f, 1f, 4f), PartPose.offsetAndRotation(0.7f, 0.8f, -2.5f, 0.25f, 0.25f, 0f));
        PartDefinition p_wing_r = p_body.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(34, 48).addBox(-24f, -1f, -1f, 24f, 2f, 2f), PartPose.offsetAndRotation(-2f, 6f, 2f, 0f, 0.3f, 0.32f));
        PartDefinition p_membrane_r = p_wing_r.addOrReplaceChild("membrane_r", CubeListBuilder.create().texOffs(40, 0).addBox(-24f, 0f, 0f, 24f, 20f, 0f), PartPose.offsetAndRotation(0f, 0.5f, 0f, 0f, 0f, 0f));
        PartDefinition p_wing2_r = p_wing_r.addOrReplaceChild("wing2_r", CubeListBuilder.create().texOffs(0, 53).addBox(-20f, -1f, -1f, 20f, 2f, 2f), PartPose.offsetAndRotation(-24f, 0f, 0f, 0f, 0f, 0.18f));
        PartDefinition p_membrane2_r = p_wing2_r.addOrReplaceChild("membrane2_r", CubeListBuilder.create().texOffs(0, 0).addBox(-20f, 0f, 0f, 20f, 26f, 0f), PartPose.offsetAndRotation(0f, 0.5f, 0f, 0f, 0f, 0f));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(48, 53).mirror().addBox(0f, -0.5f, -0.5f, 6f, 1f, 1f), PartPose.offsetAndRotation(3f, -4.8f, 0f, 0f, 0f, 0.15f));
        PartDefinition p_horn_l = p_head.addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(0, 48).mirror().addBox(-1f, -3f, -1f, 2f, 3f, 2f), PartPose.offsetAndRotation(1.8f, -8.6f, -0.5f, -0.15f, 0f, 0.35f));
        PartDefinition p_horn_l_mid = p_horn_l.addOrReplaceChild("horn_l_mid", CubeListBuilder.create().texOffs(30, 48).mirror().addBox(-0.5f, -3f, -0.5f, 1f, 3f, 1f), PartPose.offsetAndRotation(0f, -2.8f, 0f, 0.1f, 0f, -0.35f));
        PartDefinition p_horn_l_tip = p_horn_l_mid.addOrReplaceChild("horn_l_tip", CubeListBuilder.create().texOffs(44, 53).mirror().addBox(-0.5f, -2f, -0.5f, 1f, 2f, 1f), PartPose.offsetAndRotation(0f, -2.8f, 0f, 0.15f, 0f, -0.45f));
        PartDefinition p_arm_l = p_root.addOrReplaceChild("arm_l", CubeListBuilder.create().texOffs(108, 0).mirror().addBox(-1f, -1f, -1f, 2f, 13f, 2f), PartPose.offsetAndRotation(4.5f, 5.5f, 0f, 0f, 0f, -0.22f));
        PartDefinition p_forearm_l = p_arm_l.addOrReplaceChild("forearm_l", CubeListBuilder.create().texOffs(24, 26).mirror().addBox(-1f, 0f, -1f, 2f, 12f, 2f), PartPose.offsetAndRotation(0f, 12f, 0f, -0.15f, 0f, 0f));
        PartDefinition p_hand_l = p_forearm_l.addOrReplaceChild("hand_l", CubeListBuilder.create().texOffs(92, 40).mirror().addBox(-1.25f, 0f, -1.25f, 2.5f, 2.5f, 2.5f), PartPose.offsetAndRotation(0f, 12f, 0f, 0f, 0f, 0f));
        PartDefinition p_claw_l0 = p_hand_l.addOrReplaceChild("claw_l0", CubeListBuilder.create().texOffs(104, 40).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-0.9f, 2.2f, -0.5f, -0.35f, 0f, -0.27f));
        PartDefinition p_claw_l0_tip = p_claw_l0.addOrReplaceChild("claw_l0_tip", CubeListBuilder.create().texOffs(8, 48).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_claw_l1 = p_hand_l.addOrReplaceChild("claw_l1", CubeListBuilder.create().texOffs(104, 40).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(-0.3f, 2.2f, -0.5f, -0.35f, 0f, -0.09f));
        PartDefinition p_claw_l1_tip = p_claw_l1.addOrReplaceChild("claw_l1_tip", CubeListBuilder.create().texOffs(8, 48).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_claw_l2 = p_hand_l.addOrReplaceChild("claw_l2", CubeListBuilder.create().texOffs(104, 40).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(0.3f, 2.2f, -0.5f, -0.35f, 0f, 0.09f));
        PartDefinition p_claw_l2_tip = p_claw_l2.addOrReplaceChild("claw_l2_tip", CubeListBuilder.create().texOffs(8, 48).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_claw_l3 = p_hand_l.addOrReplaceChild("claw_l3", CubeListBuilder.create().texOffs(104, 40).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 5f, 1f), PartPose.offsetAndRotation(0.9f, 2.2f, -0.5f, -0.35f, 0f, 0.27f));
        PartDefinition p_claw_l3_tip = p_claw_l3.addOrReplaceChild("claw_l3_tip", CubeListBuilder.create().texOffs(8, 48).mirror().addBox(-0.5f, 0f, -0.5f, 1f, 4f, 1f), PartPose.offsetAndRotation(0f, 4.8f, 0f, -0.75f, 0f, 0f));
        PartDefinition p_leg_l = p_root.addOrReplaceChild("leg_l", CubeListBuilder.create().texOffs(88, 0).mirror().addBox(-1.25f, 0f, -1.25f, 2.5f, 14f, 2.5f), PartPose.offsetAndRotation(1.5f, 20f, 0f, 0f, 0f, 0f));
        PartDefinition p_shin_l = p_leg_l.addOrReplaceChild("shin_l", CubeListBuilder.create().texOffs(100, 0).mirror().addBox(-1f, 0f, -1f, 2f, 14f, 2f), PartPose.offsetAndRotation(0f, 14f, 0f, 0f, 0f, 0f));
        PartDefinition p_foot_l = p_shin_l.addOrReplaceChild("foot_l", CubeListBuilder.create().texOffs(108, 40).mirror().addBox(-1f, 0f, -2.5f, 2f, 1.5f, 3.5f), PartPose.offsetAndRotation(0f, 14f, 0f, 0f, 0f, 0f));
        PartDefinition p_toe_l0 = p_foot_l.addOrReplaceChild("toe_l0", CubeListBuilder.create().texOffs(12, 48).mirror().addBox(-0.5f, -0.5f, -4f, 1f, 1f, 4f), PartPose.offsetAndRotation(-0.7f, 0.8f, -2.5f, 0.25f, -0.25f, 0f));
        PartDefinition p_toe_l1 = p_foot_l.addOrReplaceChild("toe_l1", CubeListBuilder.create().texOffs(12, 48).mirror().addBox(-0.5f, -0.5f, -4f, 1f, 1f, 4f), PartPose.offsetAndRotation(0f, 0.8f, -2.5f, 0.25f, 0f, 0f));
        PartDefinition p_toe_l2 = p_foot_l.addOrReplaceChild("toe_l2", CubeListBuilder.create().texOffs(12, 48).mirror().addBox(-0.5f, -0.5f, -4f, 1f, 1f, 4f), PartPose.offsetAndRotation(0.7f, 0.8f, -2.5f, 0.25f, 0.25f, 0f));
        PartDefinition p_wing_l = p_body.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(34, 48).mirror().addBox(0f, -1f, -1f, 24f, 2f, 2f), PartPose.offsetAndRotation(2f, 6f, 2f, 0f, -0.3f, -0.32f));
        PartDefinition p_membrane_l = p_wing_l.addOrReplaceChild("membrane_l", CubeListBuilder.create().texOffs(40, 0).mirror().addBox(0f, 0f, 0f, 24f, 20f, 0f), PartPose.offsetAndRotation(0f, 0.5f, 0f, 0f, 0f, 0f));
        PartDefinition p_wing2_l = p_wing_l.addOrReplaceChild("wing2_l", CubeListBuilder.create().texOffs(0, 53).mirror().addBox(0f, -1f, -1f, 20f, 2f, 2f), PartPose.offsetAndRotation(24f, 0f, 0f, 0f, 0f, -0.18f));
        PartDefinition p_membrane2_l = p_wing2_l.addOrReplaceChild("membrane2_l", CubeListBuilder.create().texOffs(0, 0).mirror().addBox(0f, 0f, 0f, 20f, 26f, 0f), PartPose.offsetAndRotation(0f, 0.5f, 0f, 0f, 0f, 0f));
        PartDefinition p_tail1 = p_body.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(110, 26).addBox(-0.75f, -0.75f, 0f, 1.5f, 1.5f, 7f), PartPose.offsetAndRotation(0f, 18.5f, 1.5f, -1f, 0f, 0f));
        PartDefinition p_tail2 = p_tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.18f, 0.42f, 0f));
        PartDefinition p_tail3 = p_tail2.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.18f, 0.42f, 0f));
        PartDefinition p_tail4 = p_tail3.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.05f, 0.42f, 0f));
        PartDefinition p_tail5 = p_tail4.addOrReplaceChild("tail5", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.05f, 0.42f, 0f));
        PartDefinition p_tail6 = p_tail5.addOrReplaceChild("tail6", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.05f, 0.42f, 0f));
        PartDefinition p_tail7 = p_tail6.addOrReplaceChild("tail7", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.05f, 0.42f, 0f));
        PartDefinition p_tail8 = p_tail7.addOrReplaceChild("tail8", CubeListBuilder.create().texOffs(44, 40).addBox(-0.5f, -0.5f, 0f, 1f, 1f, 7f), PartPose.offsetAndRotation(0f, 0f, 6.6f, 0.05f, 0.42f, 0f));
        // </generated>
        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(ZagredBossEntity e, float limbSwing, float limbAmount, float age, float yaw, float pitch) {
        root.getAllParts().forEach(ModelPart::resetPose);
        int state = e.clientState();
        boolean fighting = state >= ZagredBossEntity.STATE_COMBAT;
        root.y += Mth.sin(age * 0.1f) * 1.2f - (e.phase() >= 2 ? 3f : 0f);
        head.yRot = yaw * Mth.DEG_TO_RAD;
        head.xRot = pitch * Mth.DEG_TO_RAD;
        if (state == ZagredBossEntity.STATE_IDLE) head.yRot += Mth.sin(age * 0.03f) * 0.25f;            // a slow, curious look round

        float walk = Mth.cos(limbSwing * 0.6662f) * limbAmount;
        legR.xRot = walk * 0.9f; legL.xRot = -walk * 0.9f;
        shinR.xRot = Math.max(0, -walk) * 0.9f; shinL.xRot = Math.max(0, walk) * 0.9f;
        armR.xRot += -walk * 0.45f; armL.xRot += walk * 0.45f;
        armR.zRot += Mth.sin(age * 0.06f) * 0.04f; armL.zRot -= Mth.sin(age * 0.06f) * 0.04f;          // breathing
        for (ModelPart c : clawsR) c.xRot -= 0.15f + 0.1f * Mth.sin(age * 0.08f);
        for (ModelPart c : clawsL) c.xRot -= 0.15f + 0.1f * Mth.sin(age * 0.08f + 1);

        float beat = Mth.sin(age * (fighting ? 0.32f : 0.11f)), lag = Mth.sin(age * (fighting ? 0.32f : 0.11f) - 0.8f);
        float spread = fighting ? 0.25f : 0.1f;
        wingR.yRot += beat * 0.35f - spread; wingL.yRot -= beat * 0.35f - spread;
        wingR.zRot += beat * 0.12f; wingL.zRot -= beat * 0.12f;
        wing2R.zRot += lag * 0.25f; wing2L.zRot -= lag * 0.25f;

        for (int k = 0; k < tail.length; k++) {
            tail[k].yRot += Mth.sin(age * 0.12f - k * 0.7f) * 0.12f;
            tail[k].xRot += Mth.sin(age * 0.07f - k * 0.5f) * 0.06f;
        }

        if (state == ZagredBossEntity.STATE_CASTING) {                        // both hands raised forward, claws spread
            armR.xRot = -1.7f; armR.zRot = 0.25f; armL.xRot = -1.7f; armL.zRot = -0.25f;
            forearmR.xRot = -0.35f; forearmL.xRot = -0.35f;
            for (int k = 0; k < 4; k++) { clawsR[k].xRot = -0.9f; clawsR[k].zRot = (k - 1.5f) * 0.3f; clawsL[k].xRot = -0.9f; clawsL[k].zRot = (k - 1.5f) * 0.3f; }
        }
        if (state == ZagredBossEntity.STATE_PORTAL) {                         // frozen mid-stride, arms thrown wide and twisting into the portal
            legR.xRot = legL.xRot = shinR.xRot = shinL.xRot = 0f;
            armR.xRot = -0.4f; armL.xRot = -0.4f; armR.zRot = 1.1f; armL.zRot = -1.1f;
            root.yRot += Mth.sin(age * 0.5f) * 0.18f;
        }
        if (attackTime > 0) {                                                // a raking claw swing
            float s = Mth.sin(attackTime * Mth.PI);
            armR.xRot = -2.4f + s * 2.6f;
            armR.yRot = -0.3f * s;
            forearmR.xRot = -0.5f * (1 - s);
        }
    }

    @Override
    public void renderToBuffer(PoseStack pose, VertexConsumer vc, int light, int overlay, int color) {
        root.render(pose, vc, light, overlay, color);
    }

    @Override
    public void translateToHand(HumanoidArm arm, PoseStack pose) {
        root.translateAndRotate(pose);
        boolean right = arm == HumanoidArm.RIGHT;
        (right ? armR : armL).translateAndRotate(pose);
        (right ? forearmR : forearmL).translateAndRotate(pose);
        (right ? handR : handL).translateAndRotate(pose);
    }
}
