"""0.49: Rouge, the cat of red thread (Thread Magic's "Red Thread of Fate: Rouge"): ONE part list -> the 32x32 texture and the
geometry of client/RougeCatModel.java (between the generated markers). A small cat sitting upright, tail curled round its paws,
woven of crimson thread with gold eyes.

    python tools/gen_rouge_cat.py
"""
import math
import os
import re

import numpy as np
from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
TEX = os.path.join(ROOT, "src", "main", "resources", "assets", "nusmp", "textures", "entity", "rouge_cat.png")
MODEL = os.path.join(ROOT, "src", "main", "java", "com", "newuniverse", "nusmp", "client", "RougeCatModel.java")
S = 32
# name, parent, pivot, rotation, boxes (u, v, x, y, z, w, h, d, mirror, material)
PARTS = [
    ("body", None, (0, 22, 0), (-0.45, 0, 0), [(0, 0, -2, -6, -2, 4, 6, 4, False, "thread")]),
    ("head", None, (0, 16.8, -1.4), (0, 0, 0), [(0, 10, -2.5, -4, -2, 5, 4, 4, False, "face"), (18, 10, -2.5, -5.5, -0.5, 1, 2, 1, False, "thread"),
                                                (18, 10, 1.5, -5.5, -0.5, 1, 2, 1, True, "thread"), (22, 13, -1, -1.6, -3, 2, 1.5, 1, False, "thread")]),
    ("leg_r", None, (-1, 19, -1.6), (0, 0, 0), [(24, 0, -0.5, 0, -0.5, 1, 5, 1, False, "thread")]),
    ("leg_l", None, (1, 19, -1.6), (0, 0, 0), [(24, 0, -0.5, 0, -0.5, 1, 5, 1, True, "thread")]),
    ("haunch_r", None, (-1.6, 22.5, 0.6), (0, 0, 0), [(0, 18, -1, -1.5, -1.5, 2, 2, 3, False, "thread")]),
    ("haunch_l", None, (1.6, 22.5, 0.6), (0, 0, 0), [(0, 18, -1, -1.5, -1.5, 2, 2, 3, True, "thread")]),
    ("tail", None, (0, 23.2, 2), (0, 0.9, 0), [(10, 18, -0.5, -0.5, 0, 1, 1, 5, False, "thread")]),
    ("tail_tip", "tail", (0, 0, 4.8), (0, 1.2, 0), [(10, 18, -0.5, -0.5, 0, 1, 1, 4, False, "thread")]),
]


def faces(u, v, w, h, d):
    return {"top": (u + d, v, w, d), "bottom": (u + d + w, v, w, d), "west": (u, v + d, d, h), "front": (u + d, v + d, w, h),
            "east": (u + d + w, v + d, d, h), "back": (u + 2 * d + w, v + d, w, h)}


def paint():
    img = np.zeros((S, S, 4), np.uint8)
    for (_, _, _, _, boxes) in PARTS:
        for (u, v, x, y, z, w, h, d, mirror, mat) in boxes:
            W, H, D = int(math.ceil(w)), int(math.ceil(h)), int(math.ceil(d))
            for fname, (fu, fv, fw, fh) in faces(u, v, W, H, D).items():
                for j in range(fh):
                    for i in range(fw):
                        X, Y = fu + i, fv + j
                        strand = (X + Y * 2) % 3
                        c = (196, 26, 38) if strand == 0 else (236, 70, 76) if strand == 1 else (124, 12, 22)   # woven red thread
                        if mat == "face" and fname == "front" and j == 1 and i in (1, 3):
                            c = (255, 210, 60)                                                                       # gold eyes
                        if mat == "face" and fname == "front" and j == 3 and i == 2:
                            c = (90, 8, 16)
                        if 0 <= X < S and 0 <= Y < S:
                            img[Y, X] = (*c, 255)
    Image.fromarray(img, "RGBA").save(TEX)
    print("wrote", TEX)


def f(x):
    s = ("%.3f" % x).rstrip("0").rstrip(".")
    return (s if s not in ("-0", "") else "0") + "f"


def java():
    var, lines = {None: "root"}, []
    for (name, parent, piv, rot, boxes) in PARTS:
        cubes = "CubeListBuilder.create()"
        for (u, v, x, y, z, w, h, d, mirror, mat) in boxes:
            cubes += ".texOffs(%d, %d)%s.addBox(%s, %s, %s, %s, %s, %s)" % (u, v, ".mirror()" if mirror else "", f(x), f(y), f(z), f(w), f(h), f(d))
        lines.append("        PartDefinition p_%s = %s.addOrReplaceChild(\"%s\", %s, PartPose.offsetAndRotation(%s, %s, %s, %s, %s, %s));"
                     % (name, var[parent], name, cubes, f(piv[0]), f(piv[1]), f(piv[2]), f(rot[0]), f(rot[1]), f(rot[2])))
        var[name] = "p_" + name
    src = open(MODEL, encoding="utf-8").read()
    src = re.sub(r"(        // <generated by tools/gen_rouge_cat.py>\n).*?(        // </generated>)", lambda m: m.group(1) + "\n".join(lines) + "\n" + m.group(2), src, flags=re.S)
    open(MODEL, "w", encoding="utf-8").write(src)
    print("wrote", len(PARTS), "parts into RougeCatModel.java")


if __name__ == "__main__":
    paint()
    java()
